# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0004_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count_hit',
            field=models.IntegerField(default=0),
        ),
    ]
