# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0005_suggestpost'),
        ('news_portal', '0005_news_count_hit'),
    ]

    operations = [
    ]
